schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "medblend"
version = "2.0.0"
name = "MedBlend"
tagline = "A medical visualization add-on for Blender"
maintainer = "Michael Douglass"
type = "add-on"
website = "https://github.com/drmichaeldouglass/MedBlend"
tags = [
	"3D View",
]
blender_version_min = "5.0.0"
license = [
  "SPDX:MIT"
]
copyright =[
	"2022-2024 Michael Douglass",
]


wheels = [
    "./wheels/certifi-2024.6.2-py3-none-any.whl",
    "./wheels/charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl",
    "./wheels/click-8.1.7-py3-none-any.whl",
    "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
    "./wheels/contourpy-1.2.1-cp311-cp311-win_amd64.whl",
    "./wheels/cycler-0.12.1-py3-none-any.whl",
    "./wheels/dataclasses-0.6-py3-none-any.whl",
    "./wheels/fonttools-4.53.0-cp311-cp311-win_amd64.whl",        
    "./wheels/idna-3.7-py3-none-any.whl",
    "./wheels/imageio-2.34.1-py3-none-any.whl",
    "./wheels/kiwisolver-1.4.5-cp311-cp311-win_amd64.whl",        
    "./wheels/lazy_loader-0.4-py3-none-any.whl",
    "./wheels/matplotlib-3.9.0-cp311-cp311-win_amd64.whl",        
    "./wheels/networkx-3.3-py3-none-any.whl",
    "./wheels/numpy-1.26.4-cp311-cp311-win_amd64.whl",
    "./wheels/opencv_python-4.10.0.82-cp37-abi3-win_amd64.whl",   
    "./wheels/packaging-24.0-py3-none-any.whl",
    "./wheels/pandas-2.2.2-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-10.3.0-cp311-cp311-win_amd64.whl",
    "./wheels/platipy-0.7.1-py3-none-any.whl",
    "./wheels/pydicom-2.4.4-py3-none-any.whl",
    "./wheels/pynetdicom-2.1.0-py3-none-any.whl",
    "./wheels/pyparsing-3.1.2-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",  
    "./wheels/pytz-2024.1-py2.py3-none-any.whl",
    "./wheels/requests-2.32.3-py3-none-any.whl",
    "./wheels/rt_utils-1.2.7-py2.py3-none-any.whl",
    "./wheels/scikit_image-0.23.2-cp311-cp311-win_amd64.whl",     
    "./wheels/scipy-1.13.1-cp311-cp311-win_amd64.whl",
    "./wheels/SimpleITK-2.3.1-cp311-cp311-win_amd64.whl",
    "./wheels/six-1.16.0-py2.py3-none-any.whl",
    "./wheels/tifffile-2024.5.22-py3-none-any.whl",
    "./wheels/tzdata-2024.1-py2.py3-none-any.whl",
    "./wheels/urllib3-2.2.1-py3-none-any.whl",
]

[permissions]
network = "Downloading structural data from the PDB and AFPDB"
files = "Importing data files from disk and caching downloads"
