schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "medblend"
version = "2.0.0"
name = "MedBlend"
tagline = "A medical visualization add-on for Blender"
maintainer = "Michael Douglass"
type = "add-on"
website = "https://github.com/drmichaeldouglass/MedBlend"
tags = [
	"3D View",
]
blender_version_min = "5.0.0"
license = [
  "SPDX:MIT"
]
copyright =[
	"2022-2024 Michael Douglass",
]


wheels = [
    "./wheels/pydicom-2.4.4-py3-none-any.whl",
]

[permissions]
network = "Downloading structural data from the PDB and AFPDB"
files = "Importing data files from disk and caching downloads"
